# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='策略名')),
                ('description', models.TextField(verbose_name='简介')),
                ('content', models.TextField(verbose_name='详情')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
            ],
        ),
    ]
