# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BQMain', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='strategy',
            name='annualizedReturn',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='年化收益率'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='authorID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='月租'),
        ),
    ]
