# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0003_auto_20170610_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='authorID',
            new_name='author',
        ),
    ]
