# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0004_auto_20170610_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='author',
            new_name='author1',
        ),
    ]
