# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0007_auto_20170612_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='annualizedReturn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='年化收益率'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='investLine',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, null=True, verbose_name='投资额度'),
        ),
    ]
