# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0009_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='scope',
        ),
        migrations.AddField(
            model_name='dealer',
            name='pop',
            field=models.IntegerField(default=0),
        ),
    ]
