# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0010_auto_20170612_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='alpha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Beta'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='beta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alpha'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='informationRatio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='信息比率'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='initialReturn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='自创建日收益'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='initialTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='portfoliosAdjustment',
            field=models.IntegerField(default=1, null=True, verbose_name='调仓周期'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='portfoliosAdjustmentNext',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下个调仓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='regressionBegin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='回测开始'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='regressionEnd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='回测结束'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='retracementMax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='最大回撤率'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sharp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='夏普比率'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='totalReturn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='总收益率'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='收益波动率'),
        ),
    ]
