# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('BQMain', '0011_auto_20170613_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, default='暂无', max_length=1000)),
                ('dealerList', models.ManyToManyField(to='BQMain.Dealer')),
                ('strategyList_subscribe', models.ManyToManyField(related_name='订阅列表', to='BQMain.Strategy')),
                ('strategyList_watch', models.ManyToManyField(related_name='关注列表', to='BQMain.Strategy')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
