# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0012_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='hot',
            field=models.IntegerField(default=0, null=True, verbose_name='热度'),
        ),
    ]
