# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0013_strategy_hot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='hot',
            new_name='viewCount',
        ),
        migrations.AddField(
            model_name='strategy',
            name='subCount',
            field=models.IntegerField(default=0, null=True, verbose_name='订阅数'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='watchCount',
            field=models.IntegerField(default=0, null=True, verbose_name='关注数'),
        ),
    ]
