# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0014_auto_20170622_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='score',
            field=models.IntegerField(default=3, verbose_name='打分'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='tags',
            field=models.ManyToManyField(related_name='Tag', to='BQMain.Tag'),
        ),
    ]
