# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0015_auto_20170622_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('crt_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BQMain.Dealer')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BQMain.Strategy')),
            ],
        ),
    ]
