# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('BQMain', '0016_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='tagMain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BQMain.Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='tags',
            field=models.ManyToManyField(related_name='标签', to='BQMain.Tag'),
        ),
    ]
