# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0018_customer_noticelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='strategyList_watch',
            new_name='strategyList_follow',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='watchCount',
            new_name='followCount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='strategyList_subscribe',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='subCount',
        ),
        migrations.AddField(
            model_name='customer',
            name='strategyList_deal',
            field=models.ManyToManyField(related_name='交易列表', to='BQMain.Strategy'),
        ),
        migrations.AddField(
            model_name='customer',
            name='strategyList_like',
            field=models.ManyToManyField(related_name='点赞列表', to='BQMain.Strategy'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='dealCount',
            field=models.IntegerField(default=0, null=True, verbose_name='交易数'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='likeCount',
            field=models.IntegerField(default=0, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dealerList',
            field=models.ManyToManyField(related_name='交易员列表', to='BQMain.Dealer'),
        ),
    ]
