# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BQMain', '0019_auto_20170717_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='code',
            field=models.CharField(default='1', max_length=20, verbose_name='策略编码'),
        ),
    ]
